------------------------------------------------
--(!!) TEST THIS
--function SymmetricalPerspectiveProjectionMatrix4x4 (FovY, R, ZNear, ZFar)
--		return Matrix4x4(  
--		1.0/(R* math.tan(FovY/2.0) ) ,
--		0,0,0,
--		
--		0,
--		1.0/(math.tan(FovY/2.0) ) 
--		,0,0,
--		
--		0,0,
--		(ZNear+ZFar)/(ZNear-ZFar),
--		-1,
--		
--		0,0,
--		(-2.0*ZNear*ZFar)/(ZNear-ZFar),		
--		0
--		)
--end
--
--
--(!!) TEST THIS
--function AsymmetricalPerspectiveProjectionMatrix (zf,zb,xl,xr,yt,yb)
--	
--
--
--end
--(!!) TEST THIS
------------------------------------------------
